### ISSUE TITLE
Do you have any example?

### ISSUE THREAD

**Issue by ahyow** [samjett247/UnwrapSharp#1]
Hi may i ask do you have any example that implement with the unwrap function?

**Comment by samjett247** [comment]
Just posted an example into the README - check out here: https://openbits.app/posts/phase-unwrap/

**Comment by ahyow** [comment]
Hi, thanks for you quick response and i have read thru the link!

I realise the example coding is in python, is there any chance i can refer the c# version??

sorry for asking again!

**Comment by samjett247** [comment]
No problem. I would just download the example datasets from the Zipped file here (these are the ones I showed in the blog post: https://openbits.app/phase-unwrap/static/UnwrapBlogPostRepeatability.zip).

Then:
- load the intensity arrays into C# using the `FileStream` built-in methods/classes in C#. You may have to convert a byte array into a float array. 
- Convert the intensity jagged arrays (float[][]) into wrapped phase array using formula (1) of the blog post
- Import the UnwrapSharp package from Nuget and specify a using directive to allow you to access UnwrapSharp inside your code.
- Use the `UnwrapSharp.Unwrap2D` method, with screenshot shown below, to unwrap the image

Lmk if this is still unclear - sorry I dont have more concrete examples!

**Comment by ahyow** [comment]
Ah thank you so much! this is very helpful!
